name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web Bundle
        run: flutter build web --release --base-href "/v_enterprise/"

      - name: Deploy to gh-pages Branch
        uses: PeaceIris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
